import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable"
import { Toaster } from "sonner";

import { ScrollArea } from "@/components/ui/scroll-area"

import Navbar from "@/components/layout/navbar";
import Leftbar from "@/components/layout/leftbar";
import { MainProvider } from "@/app/context/main-context";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "Admin Baba",
  description: "Generated by Admin Baba",
};

export default function AdminLayout({ children }) {

  return (
    <>
          <MainProvider>
            <TooltipProvider>
              <ResizablePanelGroup direction="horizontal" className="grid !h-dvh w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
                <Leftbar />
                <ResizableHandle withHandle className={`max-md:hidden`} />
                <ResizablePanel defaultSize={80} minSize={75} maxSize={97} className="flex flex-col">
                  <Navbar />
                  <ScrollArea
                    className="flex flex-1 flex-col overflow-hidden
                    [&_[data-radix-scroll-area-viewport]]:*:!flex 
                    [&_[data-radix-scroll-area-viewport]]:*:!flex-1 
                    [&_[data-radix-scroll-area-viewport]]:*:!flex-col 
                    [&_[data-radix-scroll-area-viewport]]:*:!gap-4 
                    [&_[data-radix-scroll-area-viewport]]:*:!p-4 
                    [&_[data-radix-scroll-area-viewport]]:*:!lg:gap-6 
                    [&_[data-radix-scroll-area-viewport]]:*:!lg:p-6
                    "
                  >
                    {children}
                  </ScrollArea>
                </ResizablePanel>
              </ResizablePanelGroup>
            </TooltipProvider>
          </MainProvider>
    </>
  );
}
